# Generated by Django 4.0.4 on 2022-05-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_salestatistics_sales_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='user',
        ),
        migrations.AddField(
            model_name='countries',
            name='city',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='countries',
            name='population',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='countries',
            name='rank',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
