# Generated by Django 4.0.4 on 2022-05-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_countries_user_countries_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='population',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
